//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourProj.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sight
    {
        public int SightID { get; set; }
        public string SightName { get; set; }
        public Nullable<int> CoutryID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string ImageUri { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
    }
}
