//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourProj.DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToursView
    {
        public int TourID { get; set; }
        public string TourName { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<int> TransportID { get; set; }
        public Nullable<int> MaxPeople { get; set; }
    }
}
